// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_e_commerce.Models;

#nullable disable

namespace dotnet_e_commerce.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260211062923_NewTable")]
    partial class NewTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("dotnet_e_commerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HomePage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActiv")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Apple Watch 10 is the latest smartwatch from Apple, featuring a sleek design, advanced health tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 10 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = true,
                            Image = "1.jpeg",
                            IsActiv = true,
                            Price = 499.99000000000001,
                            ProductName = "Apple Watch 10"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apple Watch 11 is the latest smartwatch from Apple, featuring a sleek design, advanced health tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 11 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = true,
                            Image = "2.jpeg",
                            IsActiv = true,
                            Price = 899.99000000000001,
                            ProductName = "Apple Watch 11"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apple Watch 12 is the latest smartwatch from Apple, featuring a sleek design, advanced health tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 12 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = false,
                            Image = "3.jpeg",
                            IsActiv = true,
                            Price = 349.99000000000001,
                            ProductName = "Apple Watch 12"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Apple Watch 13 is the latest smartwatch from Apple, featuring a sleek design, advanced health tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 13 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = false,
                            Image = "4.jpeg",
                            IsActiv = true,
                            Price = 1199.99,
                            ProductName = "Apple Watch 13"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Apple Watch 14 is the latest smartwatch from Apple, featuring a sleek design, advanced health tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 14 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = true,
                            Image = "5.jpeg",
                            IsActiv = true,
                            Price = 349.99000000000001,
                            ProductName = "Apple Watch 14"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
