// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_e_commerce.Models;

#nullable disable

namespace dotnet_e_commerce.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260314110546_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("dotnet_e_commerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Smart Watches",
                            Url = "smart-watches"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Laptops",
                            Url = "laptops"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Telephone",
                            Url = "telephone"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Headphones",
                            Url = "headphones"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Electronics",
                            Url = "electronics"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "computers",
                            Url = "computers"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "category-1",
                            Url = "category-1"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "category-2",
                            Url = "category-2"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "category-3",
                            Url = "category-3"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "category-4",
                            Url = "category-4"
                        });
                });

            modelBuilder.Entity("dotnet_e_commerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HomePage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Apple Watch 10 is the latest smartwatch from Apple, featuring a sleek design, advanced health tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 10 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = true,
                            Image = "1.jpeg",
                            IsActive = true,
                            Price = 499.99000000000001,
                            ProductName = "Apple Watch 10"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Apple Watch 11 is the latest smartwatch from Apple, featuring a sleek design, advanced health tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 11 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = true,
                            Image = "2.jpeg",
                            IsActive = false,
                            Price = 899.99000000000001,
                            ProductName = "Apple Watch 11"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Apple Watch 12 is the latest smartwatch from Apple, featuring a sleek design, advanced health tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 12 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = false,
                            Image = "3.jpeg",
                            IsActive = true,
                            Price = 349.99000000000001,
                            ProductName = "Apple Watch 12"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            Description = "Apple Watch 13 is the latest smartwatch from Apple, featuring a sleek design, advanced health tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 13 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = false,
                            Image = "4.jpeg",
                            IsActive = true,
                            Price = 1199.99,
                            ProductName = "Apple Watch 13"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Apple Watch 14 is the latest smartwatch from Apple, featuring a sleek design, advanced health tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 14 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = true,
                            Image = "5.jpeg",
                            IsActive = true,
                            Price = 349.99000000000001,
                            ProductName = "Apple Watch 14"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Description = "Apple Watch 15 is the latest smartwatch from Apple, featuring a sleek design, advanced health tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 15 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = true,
                            Image = "6.jpeg",
                            IsActive = false,
                            Price = 349.99000000000001,
                            ProductName = "Apple Watch 15"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Apple Watch 16 is the latest smartwatch from Apple, featuring a sleek design, advanced healt tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 16 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = true,
                            Image = "7.jpeg",
                            IsActive = true,
                            Price = 349.99000000000001,
                            ProductName = "Apple Watch 16"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Apple Watch 17 is the latest smartwatch from Apple, featuring a sleek design, advanced health tracking capabilities, and seamless integration with iOS devices. With its powerful performance and innovative features, the Apple Watch 17 is the perfect companion for fitness enthusiasts and tech-savvy individuals alike.",
                            HomePage = true,
                            Image = "8.jpeg",
                            IsActive = false,
                            Price = 349.99000000000001,
                            ProductName = "Apple Watch 17"
                        });
                });

            modelBuilder.Entity("dotnet_e_commerce.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Explore our wide range of cutting-edge technology products, from smartwatches to laptops, and stay ahead in the digital world.",
                            ImageUrl = "slider-1.jpeg",
                            Index = 1,
                            IsActive = true,
                            Title = "Discover the Latest Tech Trends"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Transform your daily routine with our selection of smart devices, designed to enhance convenience and connectivity in your life.",
                            ImageUrl = "slider-2.jpeg",
                            Index = 2,
                            IsActive = true,
                            Title = "Upgrade Your Lifestyle with Smart Devices"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Discover the future of technology with our innovative products that combine style, functionality, and performance for an unparalleled user experience.",
                            ImageUrl = "slider-3.jpeg",
                            Index = 3,
                            IsActive = true,
                            Title = "Experience Innovation at Your Fingertips"
                        });
                });

            modelBuilder.Entity("dotnet_e_commerce.Models.Product", b =>
                {
                    b.HasOne("dotnet_e_commerce.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("dotnet_e_commerce.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
