// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_e_commerce.Models;

#nullable disable

namespace dotnet_e_commerce.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260203044649_new-products")]
    partial class newproducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("dotnet_e_commerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HomePage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActiv")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HomePage = true,
                            IsActiv = true,
                            Price = 499.99000000000001,
                            ProductName = "Apple Watch 10"
                        },
                        new
                        {
                            Id = 2,
                            HomePage = true,
                            IsActiv = true,
                            Price = 899.99000000000001,
                            ProductName = "Apple Watch 11"
                        },
                        new
                        {
                            Id = 3,
                            HomePage = false,
                            IsActiv = true,
                            Price = 349.99000000000001,
                            ProductName = "Apple Watch 12"
                        },
                        new
                        {
                            Id = 4,
                            HomePage = false,
                            IsActiv = true,
                            Price = 1199.99,
                            ProductName = "Apple Watch 13"
                        },
                        new
                        {
                            Id = 5,
                            HomePage = true,
                            IsActiv = true,
                            Price = 349.99000000000001,
                            ProductName = "Apple Watch 14"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
